### ISSUE TITLE
[Question] QiitaAPIの記事取得に関する質問

### ISSUE THREAD

**Issue by na7ei** [shinonome-inc/qiita_client_yusei#13]
## QiitaAPIの記事取得に関する質問
- #12 

タグ詳細ページの同じ要素が表示されるバグは解決できたのですが、
Android、iOSともに、取得した記事が投稿日時(created_at)の降順になっていないことがあります。(各タグ詳細ページでこの状態が散見されます)

**この問題は、Qiita APIの仕様の問題だと思っています。一旦パスしてしまってよろしいでしょうか。**

例：「タグ：python」の詳細ページの8ページ目（各ページ20記事）
10番目のリスト（index[9]）の位置が明らかにおかしいです。
タイトルが`voicepeak邪神ちゃんとpywin32を使って邪神ちゃんがニコ生のコメントを読み上げるプログラムを作った(前編)`という記事が降順ではなくなっています。

↓Androidのタグ詳細画面
<img src="https://user-images.githubusercontent.com/78660150/227741966-1628c9b7-3f67-49d4-b941-8c0011433111.png" width="320">

↓iOSのタグ詳細画面
<img src="https://user-images.githubusercontent.com/78660150/227741857-efbe7a59-18e0-45f6-9f66-11f5cac627f2.png" width="320">

https://qiita.com/api/v2/tags/Python/items?page=8&per_page=20 

上記のリンクにアクセスし、記事の投稿日時を表す`created_at`を文字列検索してみるとわかるのですが、記事を取得した時点で、正しい順序(降順)になっていません。

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/78660150/227740761-1c7ed406-69f7-404b-bc17-b25c2f4decd5.png">

```json
# 9本目の記事→投稿日は3/20
"created_at":"2023-03-20T01:11:58+09:00","group":null,"id":"dd0cdc38982b752d45b9",
"likes_count":0,"private":false,"reactions_count":0,"stocks_count":1,
"tags":[{"name":"Python","versions":[]},{"name":"Flask","versions":[]}],
"title":"Flaskによるflashメッセージの体験",
"updated_at":"2023-03-20T01:11:58+09:00",

# 10本目の記事→投稿日は3/15
"created_at":"2023-03-15T00:24:07+09:00","group":null,"id":"08298c724865577f3dde",
"likes_count":1,"private":false,"reactions_count":0,"stocks_count":1,
"tags":[{"name":"Python","versions":[]},{"name":"Win32API","versions":[]},
{"name":"アニメ","versions":[]},{"name":"VOICEPEAK","versions":[]}],
"title":"voicepeak邪神ちゃんとpywin32を使って邪神ちゃんがニコ生のコメントを読み上げるプログラムを作った(前編)",
"updated_at":"2023-03-20T00:48:53+09:00"

# 11本目の記事→投稿日は3/20
"created_at":"2023-03-20T00:37:11+09:00","group":null,"id":"c3fc45b49c3a423bea40",
"likes_count":0,"private":false,"reactions_count":0,"stocks_count":0,
"tags":[{"name":"Python","versions":[]},{"name":"初心者","versions":[]},
{"name":"未経験","versions":[]}],
"title":"Pythonコース3周目の世界線1",
"updated_at":"2023-03-20T00:37:11+09:00",

```
> 上記のJSONを見ると`updated_at`を投稿日時として表示すればうまく降順になってくれそうな雰囲気がありますが、そうすると、今度は下記のように他の記事が降順ではなくなってしまいます。
※現時点では`created_at`で投稿日時を表示しています。

投稿日時の部分を`updated_at`で表示した場合。
<img src="https://user-images.githubusercontent.com/78660150/227742851-79beab02-926a-4d92-887e-f255bbd522b2.png" width="320">

> 12本目の記事（`ModuleNotFoundError: No module named 'MySQLdb'というタイトルの記事`）が降順ではなくなってしまします。

**Comment by Yoshida-koshi** [comment]
QiitaAPIの仕様なら仕方ないです！ちゃんとページネーションはできているので、パスしていいです！

**Comment by na7ei** [comment]
承知しました！
