### ISSUE TITLE
[bug]AndroidでWebViewが正常に動作しない

### ISSUE THREAD

**Issue by na7ei** [shinonome-inc/qiita_client_yusei#8]
## 困っていること

最終課題「Feed画面の作成 でWebViewを実装したのですが、**Android端末のみ**正常に動作しません。
**取得した詳細記事が縦に伸びてしまいます。**
※iOS Simulatorでは正常に動作します。

> ↓Androidのプレビュー
> <video src="https://user-images.githubusercontent.com/78660150/225246500-174edc5a-a987-4911-b396-faae3a11d8b1.webm"></video>

エラーログを参考にして、色々と試行錯誤してみたのですが、解決することができませんでした。
同じようなエラーに遭遇したことのある方や、解決策をご存知の方がいらっしゃいましたら、ご助言いただけますと幸いです。

対象ブランチ：[4-create_feed_screen](https://github.com/shinonome-inc/qiita_client_yusei/tree/4-create_feed_screen)
関連プルリクエスト：#7 

<br>

## 試したアプローチ

1. webview_flutter最新版（v4.0.6）を利用し、各プラットフォーム対応のコードを追記
> 対象コミット：[37f23f1](https://github.com/shinonome-inc/qiita_client_yusei/pull/7/commits/37f23f1fc2bcf36b21c350ca869fa25ae4c71128)
>  [プレビュー](https://github.com/shinonome-inc/qiita_client_yusei/pull/7#issuecomment-1463893099)

2. webview_flutterを３系にダウングレード
> 対象コミット：[763293a](https://github.com/shinonome-inc/qiita_client_yusei/pull/7/commits/763293ab2872384e1a4301f434e36bc420073965)
> [プレビュー](https://github.com/shinonome-inc/qiita_client_yusei/pull/7#issuecomment-1465578015)

<br>

### エラーログについて

WebViewを展開すると、Android Studioのエラーログには、下記のようなエラーが出ています。
`E  updateAcquireFence: Did not find frame.`というエラーが大量に出力されたので、重複したものは省略して記載しています。

```shell

16:46:35.998  E  SetHeapTaggingLevel: re-enabling tagging after it was disabled is not supported

16:46:36.008  E  updateAcquireFence: Did not find frame.

16:46:39.299  E  allocateCb:391 failed with 'Error3::NO_RESOURCES'
16:46:39.300  E  Failed to allocate (1080 x 47999) layerCount 1 format 1 usage 300: 5
16:46:39.301  E  [SurfaceTexture-0-7371-5](id:1ccb00000007,api:1,p:7371,c:7371) dequeueBuffer: createGraphicBuffer failed
16:46:39.301  E  [SurfaceTexture-0-7371-5](id:1ccb00000007,api:1,p:7371,c:7371) requestBuffer: slot 0 is not owned by the producer (state = FREE)
16:46:39.301  E  dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
16:46:39.301  E  [SurfaceTexture-0-7371-5](id:1ccb00000007,api:1,p:7371,c:7371) cancelBuffer: slot 0 is not owned by the producer (state = FREE)
16:46:39.305  E  getSlotFromBufferLocked: unknown buffer: 0x0

16:47:00.012  E  No tap action can be set up
16:47:02.617  E  Failed to getEnergyData

```

### AVDの設定について
下記のように設定したAVDを利用して、動作確認をしています。

<img width="700" alt="image" src="https://user-images.githubusercontent.com/78660150/225243017-0354463d-b867-4e8b-8baa-83070121d617.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/78660150/225243622-3d23343c-f8a6-47e7-9633-2597f04b70ff.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/78660150/225243756-f6b35e10-38d3-481e-8fa2-01aa32e064de.png">

**Comment by ShuheiYoshidaJP** [comment]
僕の環境でも同様のことが起きました。

調べたこととしましては
https://github.com/flutter/flutter/issues/119332
こちらにも似たようなエラーログが確認されたことが記されています。

僕の意見としては
ユーザーが操作できなくなったり、レイアウトが崩れるなどの致命的な不具合が確認されない限りは
このエラーログを無視していいのではと思いました。

他の講師メンバーにも相談してみようと思います。

**Comment by KobayashiYoh** [comment]
僕も今回のエラーに関しては保留で大丈夫だと思います。

**Comment by na7ei** [comment]
@ShuheiYoshidaJP さん

ご検証いただきありがとうございます！

> 僕の環境でも同様のことが起きました。
> 
> 調べたこととしましては [flutter/flutter#119332](https://github.com/flutter/flutter/issues/119332) こちらにも似たようなエラーログが確認されたことが記されています。
> 
> 僕の意見としては ユーザーが操作できなくなったり、レイアウトが崩れるなどの致命的な不具合が確認されない限りは このエラーログを無視していいのではと思いました。
> 
> 他の講師メンバーにも相談してみようと思います。


@KobayashiYoh さん


> 僕も今回のエラーに関しては保留で大丈夫だと思います。

承知しました！
この件については、一旦、保留とさせていただいて、検証するときはiOS Simulatorをメインに利用していきたいと思います！
